In [1]:
import pandas as pd

In [14]:
data = pd.read_html("https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o")[0]
data

,Unnamed: 0,Posição,País (ou território dependente),Estimativa da ONU,Crescimento desde a última estimativa,Data,Estimativa Oficial
0,NaN,1,Índia,1 429 921 746,+269.108.746,2023,Estimativa oficial
1,NaN,2,China,1 426 391 281,+87.778.313,2023,Censo oficial
2,NaN,3,Estados Unidos,339 987 103,+31.241.565,2023,Censo oficial
3,NaN,4,Indonésia,277 184 719,+33.168.546,2023,Estimativa oficial
4,NaN,5,Paquistão,240 215 932,+65.636.932,2023,Estimativa oficial
...,...,...,...,...,...,...,...
245,NaN,–,Ilha de Ascensão (Reino Unido),806,NaN,2021,Estimativa oficial[10]
246,NaN,195,Vaticano,801,NaN,2020,Estimativa oficial
247,NaN,–,Ilhas Cocos (Keeling) (Austrália),573,NaN,2020,Estimativa oficial
248,NaN,–,Tristão da Cunha (Reino Unido),241,NaN,2022,Estimativa oficial[11]
249,NaN,–,Ilhas Pitcairn (Reino Unido),63,NaN,2023,Estimativa oficial

In [12]:
len(data)

3

In [13]:
df_1 = data[0]
df_1

,Unnamed: 0,Posição,País (ou território dependente),Estimativa da ONU,Crescimento desde a última estimativa,Data,Estimativa Oficial
0,NaN,1,Índia,1 429 921 746,+269.108.746,2023,Estimativa oficial
1,NaN,2,China,1 426 391 281,+87.778.313,2023,Censo oficial
2,NaN,3,Estados Unidos,339 987 103,+31.241.565,2023,Censo oficial
3,NaN,4,Indonésia,277 184 719,+33.168.546,2023,Estimativa oficial
4,NaN,5,Paquistão,240 215 932,+65.636.932,2023,Estimativa oficial
...,...,...,...,...,...,...,...
245,NaN,–,Ilha de Ascensão (Reino Unido),806,NaN,2021,Estimativa oficial[10]
246,NaN,195,Vaticano,801,NaN,2020,Estimativa oficial
247,NaN,–,Ilhas Cocos (Keeling) (Austrália),573,NaN,2020,Estimativa oficial
248,NaN,–,Tristão da Cunha (Reino Unido),241,NaN,2022,Estimativa oficial[11]
249,NaN,–,Ilhas Pitcairn (Reino Unido),63,NaN,2023,Estimativa oficial